# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['-PhadoopVersion=2.7.0', '-PhadoopVersion=2.8.0', '-PhadoopVersion=2.9.0', '-PhadoopVersion=3.0.0', '-PhadoopVersion=3.1.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        VERSION: ${{ matrix.version }}
      run: ./gradlew clean build buildRpm buildDeb $VERSION
    - uses: codecov/codecov-action@v1
    - uses: actions/upload-artifact@v2
      with:
        name: nna_$VERSION.rpm
        path: build/distributions/*.rpm
    - uses: actions/upload-artifact@v2
      with:
        name: nna_$VERSION.deb
        path: build/distributions/*.deb
    - name: Archive and upload test reports
      run: tar -cvf reports.tar build/reports/tests/*
    - uses: actions/upload-artifact@v2
      with:
        name: reports_$VERSION.tar
        path: reports.tar
